### ISSUE TITLE
Usage not working

### ISSUE THREAD

**Issue by caduvieira** [simonsdave/clair-cicd#3]
curl -s -L https://raw.githubusercontent.com/simonsdave/clair-cicd/master/bin/assess-image-risk.sh | bash -s -- "alpine:3.5"
exiting with:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named clair_cicd

**Comment by jamiejackson** [comment]
```
$ curl -s -L https://raw.githubusercontent.com/simonsdave/clair-cicd/master/bin/assess-image-risk.sh | bash -s -- postgres
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named clair_cicd
invalid reference format
2018-08-10 22:01:37 error pulling clair image 'quay.io/coreos/clair:'
```

**Comment by simonsdave** [comment]
Finally got around to doing some more work on this repo and think you'll find the usage described in the main README.md now works.
